
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace directoriesPane {
    using Terminal.Gui;
    
    
    public partial class directoriesPane {
        
        public directoriesPane() {
            InitializeComponent();
        }
    }
}
