using Terminal.Gui.App;
using Terminal.Gui.Configuration;
using Terminal.Gui.ViewBase;
using Terminal.Gui.Views;
using Terminal.Gui.Drawing;
using tuiPlayer;
using tuiPlayer.Views;
using Terminal.Gui.Tracing;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace tuiPlayer.Views {
    using directoriesPane;
    using Terminal.Gui;
    using Terminal.Gui.Input;


    public partial class mainWindow {
        
        public mainWindow() {
            InitializeComponent();

            Bar menuBar = new()
            {
                Width = Dim.Fill(),
                Height = Dim.Auto(),
                TextAlignment = Alignment.Start,
                X = 0,
                Y = 0,
            };

            queuePane queuePane = new()
            {
                Width = Dim.Fill(),
                Height = Dim.Percent(80),
                Y = Pos.Bottom(menuBar),
                Visible = true
            };

            directoriesPane directoriesPane = new()
            {
                Width = Dim.Fill(),
                Height = Dim.Percent(80),
                Y = Pos.Bottom(menuBar),
                Visible = false
            };


            #region menuBarItems
            var queueButton = new Shortcut
            {
                Title = "_QUEUE",
                Key = Key.Q,
                Action = () =>
                {
                    queuePane.Visible = true;
                    directoriesPane.Visible = false;
                }
            };

            var directoriesButton = new Shortcut
            {
                Title = "_DIRECTORIES",
                Key = Key.D,
                Action = () =>
                {
                    queuePane.Visible = false;
                    directoriesPane.Visible = true;
                }
            };

            var artistsButton = new Shortcut
            {
                Title = "_ARTISTS",
                Key = Key.A
            };

            var albumsButton = new Shortcut
            {
                Title = "_ALBUMS",
                Key = Key.A.WithCtrl
            };

            var playlistsButton = new Shortcut
            {
                Title = "_PLAYLISTS",
                Key = Key.P
            };

            var searchButton = new Shortcut
            {
                Title = "_SEARCH",
                Key = Key.S
            };

            #endregion


            menuBar.Add(queueButton, directoriesButton, artistsButton, albumsButton, playlistsButton, searchButton);

            Add(menuBar, queuePane, directoriesPane);
           
           

        }
    }
}
