
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace tuiPlayer.Views {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class mainWindow : Terminal.Gui.Views.Runnable {
        
        private Terminal.Gui.Views.Button playStopButton;
        
        private Terminal.Gui.Views.Label songTitleLabel;
        
        private Terminal.Gui.Views.Label volumeLabel;
        
        private Terminal.Gui.Views.Label durationLabel;
        
        private Terminal.Gui.Views.Label artistAlbumLabel;
        
        private Terminal.Gui.Views.Button repeatButton;
        
        private Terminal.Gui.Views.Button shuffleButton;
        
        private Terminal.Gui.Views.Button singleButton;
        
        private Terminal.Gui.Views.ProgressBar progressBar;
        
        private Terminal.Gui.Views.MenuBar menuBar;
        
        private Terminal.Gui.Views.MenuBarItem qUEUEMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem;
        
        private Terminal.Gui.Views.MenuBarItem dIRECTORIESMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem2;
        
        private Terminal.Gui.Views.MenuBarItem aRTISTSMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem3;
        
        private Terminal.Gui.Views.MenuBarItem aLBUMSMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem4;
        
        private Terminal.Gui.Views.MenuBarItem pLAYLISTSMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem5;
        
        private Terminal.Gui.Views.MenuBarItem sEARCHMenu;
        
        private Terminal.Gui.Views.MenuItem editMeMenuItem6;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.Views.MenuBar();
            this.progressBar = new Terminal.Gui.Views.ProgressBar();
            this.singleButton = new Terminal.Gui.Views.Button();
            this.shuffleButton = new Terminal.Gui.Views.Button();
            this.repeatButton = new Terminal.Gui.Views.Button();
            this.artistAlbumLabel = new Terminal.Gui.Views.Label();
            this.durationLabel = new Terminal.Gui.Views.Label();
            this.volumeLabel = new Terminal.Gui.Views.Label();
            this.songTitleLabel = new Terminal.Gui.Views.Label();
            this.playStopButton = new Terminal.Gui.Views.Button();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.CanFocus = true;
            this.ShadowStyle = null;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.playStopButton.Width = Dim.Auto();
            this.playStopButton.Height = Dim.Auto();
            this.playStopButton.X = 0;
            this.playStopButton.Y = Pos.Top(durationLabel) - 2;
            this.playStopButton.Visible = true;
            this.playStopButton.CanFocus = true;
            this.playStopButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.playStopButton.Data = "playStopButton";
            this.playStopButton.Text = "Playing";
            this.playStopButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.playStopButton.IsDefault = false;
            this.Add(this.playStopButton);
            this.songTitleLabel.Width = Dim.Auto();
            this.songTitleLabel.Height = Dim.Auto();
            this.songTitleLabel.X = Pos.Center();
            this.songTitleLabel.Y = Pos.Top(artistAlbumLabel) - 2;
            this.songTitleLabel.Visible = true;
            this.songTitleLabel.CanFocus = false;
            this.songTitleLabel.ShadowStyle = null;
            this.songTitleLabel.Data = "songTitleLabel";
            this.songTitleLabel.Text = "Song Title";
            this.songTitleLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.songTitleLabel);
            this.volumeLabel.Width = Dim.Auto();
            this.volumeLabel.Height = Dim.Auto();
            this.volumeLabel.X = Pos.AnchorEnd() - 2;
            this.volumeLabel.Y = Pos.Top(progressBar) - 4;
            this.volumeLabel.Visible = true;
            this.volumeLabel.CanFocus = false;
            this.volumeLabel.ShadowStyle = null;
            this.volumeLabel.Data = "volumeLabel";
            this.volumeLabel.Text = "Volume 0%";
            this.volumeLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.volumeLabel);
            this.durationLabel.Width = Dim.Auto();
            this.durationLabel.Height = 1;
            this.durationLabel.X = 0;
            this.durationLabel.Y = Pos.Top(progressBar) - 2;
            this.durationLabel.Visible = true;
            this.durationLabel.CanFocus = false;
            this.durationLabel.ShadowStyle = null;
            this.durationLabel.Data = "durationLabel";
            this.durationLabel.Text = "0:00 / 0:00";
            this.durationLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.durationLabel);
            this.artistAlbumLabel.Width = Dim.Auto();
            this.artistAlbumLabel.Height = Dim.Auto();
            this.artistAlbumLabel.X = Pos.Center();
            this.artistAlbumLabel.Y = Pos.Top(progressBar) - 2;
            this.artistAlbumLabel.Visible = true;
            this.artistAlbumLabel.CanFocus = false;
            this.artistAlbumLabel.ShadowStyle = null;
            this.artistAlbumLabel.Data = "artistAlbumLabel";
            this.artistAlbumLabel.Text = "Artist - Album";
            this.artistAlbumLabel.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.artistAlbumLabel);
            this.repeatButton.Width = Dim.Auto();
            this.repeatButton.Height = Dim.Auto();
            this.repeatButton.X = Pos.Left(shuffleButton) - 11;
            this.repeatButton.Y = Pos.Top(progressBar) - 2;
            this.repeatButton.Visible = true;
            this.repeatButton.CanFocus = true;
            this.repeatButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.repeatButton.Data = "repeatButton";
            this.repeatButton.Text = "Repeat";
            this.repeatButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.repeatButton.IsDefault = false;
            this.Add(this.repeatButton);
            this.shuffleButton.Width = Dim.Auto();
            this.shuffleButton.Height = Dim.Auto();
            this.shuffleButton.X = Pos.Left(singleButton) - 12;
            this.shuffleButton.Y = Pos.Top(progressBar) - 2;
            this.shuffleButton.Visible = true;
            this.shuffleButton.CanFocus = true;
            this.shuffleButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.shuffleButton.Data = "shuffleButton";
            this.shuffleButton.Text = "Shuffle";
            this.shuffleButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.shuffleButton.IsDefault = false;
            this.Add(this.shuffleButton);
            this.singleButton.Width = Dim.Auto();
            this.singleButton.Height = Dim.Auto();
            this.singleButton.X = Pos.AnchorEnd() - 1;
            this.singleButton.Y = Pos.Top(progressBar) - 2;
            this.singleButton.Visible = true;
            this.singleButton.CanFocus = true;
            this.singleButton.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.singleButton.Data = "singleButton";
            this.singleButton.Text = "Single";
            this.singleButton.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.singleButton.IsDefault = false;
            this.Add(this.singleButton);
            this.progressBar.Width = Dim.Fill();
            this.progressBar.Height = 1;
            this.progressBar.X = 0;
            this.progressBar.Y = Pos.AnchorEnd();
            this.progressBar.Visible = true;
            this.progressBar.CanFocus = false;
            this.progressBar.ShadowStyle = null;
            this.progressBar.Data = "progressBar";
            this.progressBar.Text = "100%";
            this.progressBar.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.progressBar.Fraction = 1F;
            this.progressBar.BidirectionalMarquee = true;
            this.progressBar.ProgressBarStyle = Terminal.Gui.Views.ProgressBarStyle.Continuous;
            this.progressBar.ProgressBarFormat = Terminal.Gui.Views.ProgressBarFormat.Simple;
            this.progressBar.SegmentCharacter = new System.Text.Rune('█');
            this.Add(this.progressBar);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = Dim.Auto();
            this.menuBar.X = -1;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.CanFocus = false;
            this.menuBar.ShadowStyle = null;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.qUEUEMenu = new Terminal.Gui.Views.MenuBarItem();
            this.qUEUEMenu.Title = "QUEUE";
            this.editMeMenuItem = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.qUEUEMenu.PopoverMenu = new PopoverMenu([editMeMenuItem]);
            this.menuBar.Add(this.qUEUEMenu);
            this.dIRECTORIESMenu = new Terminal.Gui.Views.MenuBarItem();
            this.dIRECTORIESMenu.Title = "DIRECTORIES";
            this.editMeMenuItem2 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem2.Title = "Edit Me";
            this.dIRECTORIESMenu.PopoverMenu = new PopoverMenu([editMeMenuItem2]);
            this.menuBar.Add(this.dIRECTORIESMenu);
            this.aRTISTSMenu = new Terminal.Gui.Views.MenuBarItem();
            this.aRTISTSMenu.Title = "ARTISTS";
            this.editMeMenuItem3 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem3.Title = "Edit Me";
            this.aRTISTSMenu.PopoverMenu = new PopoverMenu([editMeMenuItem3]);
            this.menuBar.Add(this.aRTISTSMenu);
            this.aLBUMSMenu = new Terminal.Gui.Views.MenuBarItem();
            this.aLBUMSMenu.Title = "ALBUMS";
            this.editMeMenuItem4 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem4.Title = "Edit Me";
            this.aLBUMSMenu.PopoverMenu = new PopoverMenu([editMeMenuItem4]);
            this.menuBar.Add(this.aLBUMSMenu);
            this.pLAYLISTSMenu = new Terminal.Gui.Views.MenuBarItem();
            this.pLAYLISTSMenu.Title = "PLAYLISTS";
            this.editMeMenuItem5 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem5.Title = "Edit Me";
            this.pLAYLISTSMenu.PopoverMenu = new PopoverMenu([editMeMenuItem5]);
            this.menuBar.Add(this.pLAYLISTSMenu);
            this.sEARCHMenu = new Terminal.Gui.Views.MenuBarItem();
            this.sEARCHMenu.Title = "SEARCH";
            this.editMeMenuItem6 = new Terminal.Gui.Views.MenuItem();
            this.editMeMenuItem6.Title = "Edit Me";
            this.sEARCHMenu.PopoverMenu = new PopoverMenu([editMeMenuItem6]);
            this.menuBar.Add(this.sEARCHMenu);
            this.Add(this.menuBar);
        }
    }
}
