using Terminal.Gui.App;
using Terminal.Gui.Configuration;
using Terminal.Gui.ViewBase;
using Terminal.Gui.Views;
using tuiPlayer;
using tuiPlayer.Views;
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace tuiPlayer.Views {
    using Terminal.Gui;
    
    
    public partial class mainWindow {
        
        public mainWindow() {
            InitializeComponent();

            //songTitleLabel.X = Pos.Center();
            


        }
    }
}
