
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace tuiPlayer.Views {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class queuePane : Terminal.Gui.ViewBase.View {
        
        private Terminal.Gui.Views.TableView tableView;
        
        private Terminal.Gui.Views.Button button;
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.Label label5;
        
        private Terminal.Gui.Views.Label label4;
        
        private Terminal.Gui.Views.Label label3;
        
        private Terminal.Gui.Views.Label label2;
        
        private Terminal.Gui.Views.Button button3;
        
        private Terminal.Gui.Views.Button button2;
        
        private Terminal.Gui.Views.ProgressBar progressBar;
        
        private void InitializeComponent() {
            this.progressBar = new Terminal.Gui.Views.ProgressBar();
            this.button2 = new Terminal.Gui.Views.Button();
            this.button3 = new Terminal.Gui.Views.Button();
            this.label2 = new Terminal.Gui.Views.Label();
            this.label3 = new Terminal.Gui.Views.Label();
            this.label4 = new Terminal.Gui.Views.Label();
            this.label5 = new Terminal.Gui.Views.Label();
            this.label = new Terminal.Gui.Views.Label();
            this.button = new Terminal.Gui.Views.Button();
            this.tableView = new Terminal.Gui.Views.TableView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.CanFocus = false;
            this.ShadowStyle = null;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.tableView.Width = 89;
            this.tableView.Height = 38;
            this.tableView.X = 65;
            this.tableView.Y = 2;
            this.tableView.Visible = true;
            this.tableView.CanFocus = true;
            this.tableView.ShadowStyle = null;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.tableView.FullRowSelect = false;
            this.tableView.Style.AlwaysShowHeaders = false;
            this.tableView.Style.ExpandLastColumn = true;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableColumn0;
            tableViewTableColumn0 = new System.Data.DataColumn();
            tableViewTableColumn0.ColumnName = "Column 0";
            tableViewTable.Columns.Add(tableViewTableColumn0);
            System.Data.DataColumn tableViewTableColumn1;
            tableViewTableColumn1 = new System.Data.DataColumn();
            tableViewTableColumn1.ColumnName = "Column 1";
            tableViewTable.Columns.Add(tableViewTableColumn1);
            System.Data.DataColumn tableViewTableColumn2;
            tableViewTableColumn2 = new System.Data.DataColumn();
            tableViewTableColumn2.ColumnName = "Column 2";
            tableViewTable.Columns.Add(tableViewTableColumn2);
            System.Data.DataColumn tableViewTableColumn3;
            tableViewTableColumn3 = new System.Data.DataColumn();
            tableViewTableColumn3.ColumnName = "Column 3";
            tableViewTable.Columns.Add(tableViewTableColumn3);
            this.tableView.Table = new Terminal.Gui.Views.DataTableSource(tableViewTable);
            this.Add(this.tableView);
            this.button.Width = Dim.Auto();
            this.button.Height = Dim.Auto();
            this.button.X = 2;
            this.button.Y = 41;
            this.button.Visible = true;
            this.button.CanFocus = true;
            this.button.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.button.Data = "button";
            this.button.Text = "PlayingOrNot";
            this.button.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button.IsDefault = false;
            this.Add(this.button);
            this.label.Width = Dim.Auto();
            this.label.Height = Dim.Auto();
            this.label.X = 74;
            this.label.Y = 41;
            this.label.Visible = true;
            this.label.CanFocus = false;
            this.label.ShadowStyle = null;
            this.label.Data = "label";
            this.label.Text = "SongTitle";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label);
            this.label5.Width = Dim.Auto();
            this.label5.Height = Dim.Auto();
            this.label5.X = Pos.Center();
            this.label5.Y = 41;
            this.label5.Visible = true;
            this.label5.CanFocus = false;
            this.label5.ShadowStyle = null;
            this.label5.Data = "label5";
            this.label5.Text = "Volume: 0%";
            this.label5.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label5);
            this.label4.Width = Dim.Auto();
            this.label4.Height = Dim.Auto();
            this.label4.X = 2;
            this.label4.Y = 43;
            this.label4.Visible = true;
            this.label4.CanFocus = false;
            this.label4.ShadowStyle = null;
            this.label4.Data = "label4";
            this.label4.Text = "0:00 / 0:00";
            this.label4.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label4);
            this.label3.Width = Dim.Auto();
            this.label3.Height = Dim.Auto();
            this.label3.X = 73;
            this.label3.Y = 43;
            this.label3.Visible = true;
            this.label3.CanFocus = false;
            this.label3.ShadowStyle = null;
            this.label3.Data = "label3";
            this.label3.Text = "ArtistAlbum";
            this.label3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label3);
            this.label2.Width = Dim.Auto();
            this.label2.Height = 0;
            this.label2.X = 76;
            this.label2.Y = 43;
            this.label2.Visible = true;
            this.label2.CanFocus = false;
            this.label2.ShadowStyle = null;
            this.label2.Data = "label2";
            this.label2.Text = "Heya";
            this.label2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label2);
            this.button3.Width = Dim.Auto();
            this.button3.Height = Dim.Auto();
            this.button3.X = 132;
            this.button3.Y = 43;
            this.button3.Visible = true;
            this.button3.CanFocus = true;
            this.button3.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.button3.Data = "button3";
            this.button3.Text = "Shuffle";
            this.button3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button3.IsDefault = false;
            this.Add(this.button3);
            this.button2.Width = Dim.Auto();
            this.button2.Height = Dim.Auto();
            this.button2.X = 144;
            this.button2.Y = 43;
            this.button2.Visible = true;
            this.button2.CanFocus = true;
            this.button2.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.Opaque;
            this.button2.Data = "button2";
            this.button2.Text = "Repeat";
            this.button2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.button2.IsDefault = false;
            this.Add(this.button2);
            this.progressBar.Width = Dim.Fill();
            this.progressBar.Height = 1;
            this.progressBar.X = 2;
            this.progressBar.Y = 45;
            this.progressBar.Visible = true;
            this.progressBar.CanFocus = false;
            this.progressBar.ShadowStyle = null;
            this.progressBar.Data = "progressBar";
            this.progressBar.Text = "100%";
            this.progressBar.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.progressBar.Fraction = 1F;
            this.progressBar.BidirectionalMarquee = true;
            this.progressBar.ProgressBarStyle = Terminal.Gui.Views.ProgressBarStyle.MarqueeContinuous;
            this.progressBar.ProgressBarFormat = Terminal.Gui.Views.ProgressBarFormat.Simple;
            this.progressBar.SegmentCharacter = new System.Text.Rune('█');
            this.Add(this.progressBar);
        }
    }
}
