
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.4.5.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace tuiPlayer.Views {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class queuePane : Terminal.Gui.ViewBase.View {
        
        private Terminal.Gui.Views.TableView queueTable;
        
        private Terminal.Gui.Views.ImageView imageView;
        
        private Terminal.Gui.Views.ImageView songCover;
        
        private Terminal.Gui.Views.Label label2;
        
        private void InitializeComponent() {
            this.label2 = new Terminal.Gui.Views.Label();
            this.songCover = new Terminal.Gui.Views.ImageView();
            this.imageView = new Terminal.Gui.Views.ImageView();
            this.queueTable = new Terminal.Gui.Views.TableView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.CanFocus = false;
            this.ShadowStyle = null;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.queueTable.Width = Dim.Fill(64 + 9);
            this.queueTable.Height = Dim.Percent(99);
            this.queueTable.X = 0;
            this.queueTable.Y = 1;
            this.queueTable.Visible = true;
            this.queueTable.CanFocus = true;
            this.queueTable.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyles.None;
            this.queueTable.Data = "queueTable";
            this.queueTable.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.queueTable.FullRowSelect = true;
            this.queueTable.Style.AlwaysShowHeaders = false;
            this.queueTable.Style.ExpandLastColumn = true;
            this.queueTable.Style.InvertSelectedCellFirstCharacter = false;
            this.queueTable.Style.ShowHorizontalHeaderOverline = false;
            this.queueTable.Style.ShowHorizontalHeaderUnderline = false;
            this.queueTable.Style.ShowVerticalCellLines = true;
            this.queueTable.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable queueTableTable;
            queueTableTable = new System.Data.DataTable();
            System.Data.DataColumn queueTableTableArtist;
            queueTableTableArtist = new System.Data.DataColumn();
            queueTableTableArtist.ColumnName = "Artist";
            queueTableTable.Columns.Add(queueTableTableArtist);
            System.Data.DataColumn queueTableTableTitle;
            queueTableTableTitle = new System.Data.DataColumn();
            queueTableTableTitle.ColumnName = "Title";
            queueTableTable.Columns.Add(queueTableTableTitle);
            System.Data.DataColumn queueTableTableAlbum;
            queueTableTableAlbum = new System.Data.DataColumn();
            queueTableTableAlbum.ColumnName = "Album";
            queueTableTable.Columns.Add(queueTableTableAlbum);
            System.Data.DataColumn queueTableTableDuration;
            queueTableTableDuration = new System.Data.DataColumn();
            queueTableTableDuration.ColumnName = "Duration";
            queueTableTable.Columns.Add(queueTableTableDuration);
            this.queueTable.Table = new Terminal.Gui.Views.DataTableSource(queueTableTable);
            this.Add(this.queueTable);
            this.imageView.Width = Dim.Fill(0);
            this.imageView.Height = Dim.Fill(0);
            this.imageView.X = Pos.Right(queueTable);
            this.imageView.Y = 1;
            this.imageView.Visible = true;
            this.imageView.CanFocus = true;
            this.imageView.ShadowStyle = null;
            this.imageView.Data = "imageView";
            this.imageView.Text = "";
            this.imageView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.imageView);
            this.songCover.Width = 64;
            this.songCover.Height = 32;
            this.songCover.X = Pos.AnchorEnd() - 5;
            this.songCover.Y = Pos.Center() + 2;
            this.songCover.Visible = true;
            this.songCover.CanFocus = false;
            this.songCover.ShadowStyle = null;
            this.songCover.Data = "songCover";
            this.songCover.Text = "";
            this.songCover.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.songCover);
            this.label2.Width = Dim.Auto();
            this.label2.Height = 0;
            this.label2.X = 76;
            this.label2.Y = 43;
            this.label2.Visible = true;
            this.label2.CanFocus = false;
            this.label2.ShadowStyle = null;
            this.label2.Data = "label2";
            this.label2.Text = "Heya";
            this.label2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Center;
            this.Add(this.label2);
        }
    }
}
